# Generated by Django 3.2.25 on 2026-04-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20260410_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('item_name', models.CharField(max_length=200)),
                ('food_image', models.ImageField(upload_to='food_images/')),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('safety_declaration', models.BooleanField(default=False)),
            ],
        ),
    ]
